version: '2'
services:
  gofabric8:
    image: yurifl/gofabric8
    build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile.test
    working_dir: /home
    ports:
      - 80:80
    volumes:
      - ./:/home
